worker_processes 1;

events {
    worker_connections 1024;
}

http {
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
    listen       80;
    server_name cipherroad.localhost;
  
    etag on;
    add_header Cache-Control "max-age=86400";
    
    root $client_build;
    index index.html;
    
    # Serve client build directly from Nginx
    location / {
        try_files $uri $uri/ /index.html = 404;
    }

    # Error handling
    error_page 404 /404.html;
    location = /404.html {
        root html; # Path to the directory where 404.html is located
        internal;
    }

    # Location block to serve the error page
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root html; # Path to the directory where 50x.html is located
        internal;
    }
}
}